---
abstract: 'import Lingr chat texts into BusyBird'
author:
  - 'Toshio Ito <toshioito@cpan.org>'
build_requires:
  Test::Deep: '0.084'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
  Module::Build::Prereqs::FromCPANfile: '0.02'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: BusyBird-Input-Lingr
no_index:
  directory:
    - t
    - xt
    - eg
    - inc
  file:
    - README.pod
requires:
  BusyBird::DateTime::Format: '0.04'
  Carp: '0'
  DateTime::Format::ISO8601: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/debug-ito/BusyBird-Input-Lingr/issues
  repository: git://github.com/debug-ito/BusyBird-Input-Lingr.git
version: '0.02'
